# FROM nginx
# RUN rm -rf /usr/share/nginx/html/index.html
# COPY index.html /usr/share/nginx/html/index.html
# #COPY qi/ /usr/share/nginx/html/
# # CMD ["sleep", "1000"]

FROM nginx
RUN rm -rf /usr/share/nginx/html/index.thm
COPY index.html /usr/share/nginx/html/index.html
